/**
 * BifrostLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationUserDepartmentId } from './applicationUserDepartmentId';
import { BatchUpdateChoiceDto } from './batchUpdateChoiceDto';


export interface BatchUpdateQuestionDto { 
    id?: ApplicationUserDepartmentId | null;
    text?: string;
    choices?: Array<BatchUpdateChoiceDto>;
}

