/**
 * WellaLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BatchUpdateQuestionDto } from './batchUpdateQuestionDto';


export interface BatchUpdateQuizDto { 
    title?: string;
    description?: string | null;
    questions?: Array<BatchUpdateQuestionDto>;
}

