/**
 * WellaLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BatchUpdateChoiceDtoId } from './batchUpdateChoiceDtoId';
import { BatchUpdateChoiceDto } from './batchUpdateChoiceDto';


export interface BatchUpdateQuestionDto { 
    id?: BatchUpdateChoiceDtoId | null;
    text?: string;
    choices?: Array<BatchUpdateChoiceDto>;
}

