/**
 * BifrostLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationUserDepartmentId } from './applicationUserDepartmentId';
import { ApiCoursesIdGetIdParameter } from './apiCoursesIdGetIdParameter';
import { LessonProgressDto } from './lessonProgressDto';


export interface CourseProgressDto { 
    courseId?: ApiCoursesIdGetIdParameter;
    courseTitle?: string;
    progressPercentage?: ApiCoursesIdGetIdParameter;
    isStarted?: boolean;
    quizId?: ApplicationUserDepartmentId | null;
    hasQuiz?: boolean;
    isQuizPassed?: boolean;
    lessons?: Array<LessonProgressDto>;
}

