/**
 * BifrostLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BatchUpdateChoiceDtoId } from './batchUpdateChoiceDtoId';


export interface CreateQuizDto { 
    title?: string;
    description?: string | null;
    timeLimitMinutes?: BatchUpdateChoiceDtoId | null;
    numberOfQuestionsToServe?: BatchUpdateChoiceDtoId | null;
}

