/**
 * BifrostLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationUserDepartmentId } from './applicationUserDepartmentId';


export interface CreateDepartmentDto { 
    name?: string;
    description?: string | null;
    parentDepartmentId?: ApplicationUserDepartmentId | null;
}

