/**
 * BifrostLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationUser } from './applicationUser';
import { ApplicationUserDepartmentId } from './applicationUserDepartmentId';
import { ApiCoursesIdGetIdParameter } from './apiCoursesIdGetIdParameter';
import { DepartmentRoute } from './departmentRoute';


export interface Department { 
    name?: string;
    description?: string | null;
    parentDepartmentId?: ApplicationUserDepartmentId | null;
    subDepartments?: Array<Department>;
    students?: Array<ApplicationUser>;
    departmentRoutes?: Array<DepartmentRoute>;
    id?: ApiCoursesIdGetIdParameter;
    tenantId?: string | null;
    createdAt?: string;
    updatedAt?: string | null;
}

