/**
 * BifrostLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiCoursesIdGetIdParameter } from './apiCoursesIdGetIdParameter';
import { Route } from './route';


export interface DepartmentRoute { 
    departmentId?: ApiCoursesIdGetIdParameter;
    routeId?: ApiCoursesIdGetIdParameter;
    route?: Route;
    tenantId?: string | null;
}

