/**
 * BifrostLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationUserDepartmentId } from './applicationUserDepartmentId';
import { ApiCoursesIdGetIdParameter } from './apiCoursesIdGetIdParameter';
import { RouteDto } from './routeDto';


export interface DepartmentDto { 
    id?: ApiCoursesIdGetIdParameter;
    name?: string;
    description?: string | null;
    parentDepartmentId?: ApplicationUserDepartmentId | null;
    subDepartments?: Array<DepartmentDto>;
    assignedRoutes?: Array<RouteDto>;
}

