/**
 * BifrostLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiCoursesIdGetIdParameter } from './apiCoursesIdGetIdParameter';
import { ChoiceDto } from './choiceDto';


export interface QuestionDto { 
    id?: ApiCoursesIdGetIdParameter;
    text?: string;
    choices?: Array<ChoiceDto>;
}

