/**
 * BifrostLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiCoursesIdGetIdParameter } from './apiCoursesIdGetIdParameter';
import { QuestionDto } from './questionDto';


export interface QuizDto { 
    id?: ApiCoursesIdGetIdParameter;
    title?: string;
    description?: string | null;
    questions?: Array<QuestionDto>;
}

