/**
 * BifrostLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiCoursesIdGetIdParameter } from './apiCoursesIdGetIdParameter';
import { QuestionAnswerDto } from './questionAnswerDto';


export interface QuizSubmissionDto { 
    quizId?: ApiCoursesIdGetIdParameter;
    answers?: Array<QuestionAnswerDto>;
}

