/**
 * BifrostLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterDto { 
    username?: string;
    password?: string;
    fullName?: string;
    role?: string;
}

