/**
 * BifrostLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiCoursesIdGetIdParameter } from './apiCoursesIdGetIdParameter';
import { RouteCourseDto } from './routeCourseDto';


export interface RouteDto { 
    id?: ApiCoursesIdGetIdParameter;
    name?: string;
    description?: string | null;
    courses?: Array<RouteCourseDto>;
}

