/**
 * BifrostLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RouteCourse } from './routeCourse';
import { ApiCoursesIdGetIdParameter } from './apiCoursesIdGetIdParameter';
import { DepartmentRoute } from './departmentRoute';


export interface Route { 
    name?: string;
    description?: string | null;
    routeCourses?: Array<RouteCourse>;
    departmentRoutes?: Array<DepartmentRoute>;
    id?: ApiCoursesIdGetIdParameter;
    tenantId?: string | null;
    createdAt?: string;
    updatedAt?: string | null;
}

