/**
 * BifrostLms.Api | v1
 *
 * NOTE: This class is auto generated by simulation.
 */

export interface Schedule {
  id: number;
  tenantId?: string | null;
  createdAt: string;
  updatedAt?: string | null;
  title: string;
  startTime: string;
  endTime: string;
  location?: string | null;
  meetingUrl?: string | null;
}
