/**
 * WellaLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationUser } from './applicationUser';
import { ApiCoursesIdGetIdParameter } from './apiCoursesIdGetIdParameter';
import { Course } from './course';
import { QuizResultDtoScore } from './quizResultDtoScore';


export interface StudentProgress { 
    studentId?: string;
    student?: ApplicationUser;
    courseId?: ApiCoursesIdGetIdParameter;
    course?: Course;
    progressPercentage?: ApiCoursesIdGetIdParameter;
    score?: QuizResultDtoScore;
    id?: ApiCoursesIdGetIdParameter;
    tenantId?: string | null;
    createdAt?: string;
    updatedAt?: string | null;
}

