/**
 * WellaLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiCoursesIdGetIdParameter } from './apiCoursesIdGetIdParameter';
import { QuizResultDtoScore } from './quizResultDtoScore';


export interface TeacherQuizAttemptDto { 
    id?: ApiCoursesIdGetIdParameter;
    studentName?: string;
    quizId?: ApiCoursesIdGetIdParameter;
    quizTitle?: string;
    score?: QuizResultDtoScore;
    isPassed?: boolean;
    completedAt?: string;
}

