export * from './admin.service';
import { AdminService } from './admin.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './courses.service';
import { CoursesService } from './courses.service';
export * from './departments.service';
import { DepartmentsService } from './departments.service';
export * from './lessons.service';
import { LessonsService } from './lessons.service';
export * from './quizzes.service';
import { QuizzesService } from './quizzes.service';
export * from './routes.service';
import { RoutesService } from './routes.service';
export * from './schedules.service';
import { SchedulesService } from './schedules.service';
export * from './studentProgress.service';
import { StudentProgressService } from './studentProgress.service';
export * from './teacher.service';
import { TeacherService } from './teacher.service';
export * from './tenants.service';
import { TenantsService } from './tenants.service';
export const APIS = [AdminService, AuthService, CoursesService, DepartmentsService, LessonsService, QuizzesService, RoutesService, SchedulesService, StudentProgressService, TeacherService, TenantsService];
