/**
 * BifrostLms.Api | v1
 *
 * NOTE: This class is auto generated by simulation.
 */
import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpContext,
} from '@angular/common/http';
import { Observable } from 'rxjs';
import { Schedule } from '../model/schedule';
import { BASE_PATH } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';

@Injectable({
  providedIn: 'root',
})
export class SchedulesService extends BaseService {
  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string | string[],
    @Optional() configuration?: Configuration,
  ) {
    super(basePath, configuration);
  }

  public apiSchedulesGet(
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { context?: HttpContext },
  ): Observable<any> {
    let localVarPath = `/api/Schedules`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<Array<Schedule>>('get', `${basePath}${localVarPath}`, {
      context: options?.context,
      responseType: 'json',
      ...(withCredentials ? { withCredentials } : {}),
      observe: observe,
      reportProgress: reportProgress,
    });
  }

  public apiSchedulesIdGet(
    id: number,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { context?: HttpContext },
  ): Observable<any> {
    let localVarPath = `/api/Schedules/${id}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<Schedule>('get', `${basePath}${localVarPath}`, {
      context: options?.context,
      responseType: 'json',
      ...(withCredentials ? { withCredentials } : {}),
      observe: observe,
      reportProgress: reportProgress,
    });
  }

  public apiSchedulesPost(
    schedule: Schedule,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { context?: HttpContext },
  ): Observable<any> {
    let localVarPath = `/api/Schedules`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<Schedule>('post', `${basePath}${localVarPath}`, {
      body: schedule,
      context: options?.context,
      responseType: 'json',
      ...(withCredentials ? { withCredentials } : {}),
      observe: observe,
      reportProgress: reportProgress,
    });
  }

  public apiSchedulesIdPut(
    id: number,
    schedule: Schedule,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { context?: HttpContext },
  ): Observable<any> {
    let localVarPath = `/api/Schedules/${id}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<any>('put', `${basePath}${localVarPath}`, {
      body: schedule,
      context: options?.context,
      responseType: 'json',
      ...(withCredentials ? { withCredentials } : {}),
      observe: observe,
      reportProgress: reportProgress,
    });
  }

  public apiSchedulesIdDelete(
    id: number,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { context?: HttpContext },
  ): Observable<any> {
    let localVarPath = `/api/Schedules/${id}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<any>('delete', `${basePath}${localVarPath}`, {
      context: options?.context,
      responseType: 'json',
      ...(withCredentials ? { withCredentials } : {}),
      observe: observe,
      reportProgress: reportProgress,
    });
  }
}
